---

- name: MONGODB CONFIG TASK | Ensure That Host Directories Exist
  file:
    path: "{{ item.host_dir }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ mongodb_directories }}"
  notify:
    - "restart_mongodb_docker_auth"
    - "restart_mongodb_docker_no_auth" 
    - "restart_mongodb_host_auth"
    - "restart_mongodb_host_no_auth"

- name: MONGODB CONFIG TASK | Ensure That Config Files Exist
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ mongodb_files }}"
  notify:
    - "restart_mongodb_docker_auth"
    - "restart_mongodb_docker_no_auth" 
    - "restart_mongodb_host_auth"
    - "restart_mongodb_host_no_auth"

- debug:
    msg: "Safe Mode Status: {{ mongodb_safe_mode | default('False') }}"
