---

- name: MONGODB POST INSTALLATION TASK | Create Users [Node FQDN Address]
  mongodb_user:
    database: "{{ item.database }}"
    login_host: "{{ mongodb_login_host }}"
    login_port: "{{ mongodb_login_port }}"
    login_user: "{{ mongodb_secret_vars['admin_user'] }}"
    login_password: "{{ mongodb_secret_vars['admin_password'] }}"
    user: "{{ item.user }}"
    password: "{{ item.password }}"
    roles: "{{ item.roles }}"
    state: present
  no_log: true
  changed_when: false
  with_items: "{{ mongodb_users }}"
  when:
    - mongodb_security is defined and mongodb_security == "enabled"
    - mongodb_master_address is defined
    - mongodb_replica_set_use_dns is defined and mongodb_replica_set_use_dns == true

- name: MONGODB POST INSTALLATION TASK | Create Users [Node IP Address]
  mongodb_user:
    database: "{{ item.database }}"
    login_host: "{{ mongodb_login_host }}"
    login_port: "{{ mongodb_login_port }}"
    login_user: "{{ mongodb_secret_vars['admin_user'] }}"
    login_password: "{{ mongodb_secret_vars['admin_password'] }}"
    user: "{{ item.user }}"
    password: "{{ item.password }}"
    roles: "{{ item.roles }}"
    state: present
  no_log: true
  changed_when: false
  with_items: "{{ mongodb_users }}"
  when:
    - mongodb_security is defined and mongodb_security == "enabled"
    - mongodb_master_address is defined
    - (mongodb_replica_set_use_dns is defined and mongodb_replica_set_use_dns == false) or mongodb_replica_set_use_dns is not defined
