---

- name: MONGODB DOCKER TASK | Ensure That Docker Networks Exist
  docker_network:
    name: "{{ item.name }}"
  with_items: "{{ mongodb_config['docker_opts']['networks'] }}"

- name: MONGODB DOCKER TASK | Start Docker Container
  docker_container:
    name: "{{ mongodb_config['docker_opts']['container_name'] }}"
    image: "{{ mongodb_config['docker_opts']['image_name'] }}:{{ mongodb_config['docker_opts']['image_tag'] }}"
    state: started
    restart_policy: always
    detach: yes
    interactive: yes
    tty: yes
    command: "{{ mongodb_config['docker_opts']['command'] | default(omit) }}"
    ports: "{{ mongodb_config['docker_opts']['ports'] | default(omit) }}"
    env: "{{ mongodb_config['docker_opts']['env_vars'] | default(omit) }}"
    volumes: "{{ mongodb_config['docker_opts']['volumes'] | default(omit) }}"
    log_driver: "{{ mongodb_config['docker_opts']['log_driver']| default(omit) }}"
    hostname: "{{ mongodb_config['docker_opts']['hostname']| default(omit) }}"
    network_mode: "{{ mongodb_config['docker_opts']['network_mode']| default(omit) }}"
    networks: "{{ mongodb_config['docker_opts']['networks'] | default(omit) }}"
    purge_networks: "{{ mongodb_config['docker_opts']['purge_networks'] | default(omit) }}"
